#!/bin/bash
if [ -z "$SPARK_HOME" ]; then
   echo "$(tput setaf 1)Error: SPARK_HOME is not set, can not run tests.$(tput sgr0)"
   exit -1
fi
JARS=`ls ./target/scala-2.10/*.jar`
PYSPARK_SUBMIT_ARGS="--jars $JARS --driver-class-path $JARS" PYTHON_PATH=./ nosetests --logging-level=INFO --detailed-errors --verbosity=2 --with-coverage --cover-html-dir=./htmlcov --cover-package=sparklingpandas
