#!/bin/bash
set -x
sudo apt-get update &> /dev/null &
UPDATE_PID=$!
wget http://d3kbcqa49mib13.cloudfront.net/spark-1.4.1-bin-hadoop2.4.tgz &> downlaod &
WGET_PID=$!
./sbt/sbt assembly &> assembly &
ASSEMBLY_PID=$!
wait UPDATE_PID || echo "update finished"
sudo aptitude install liblapack-dev  libblas-dev liblapack-3gf.so libblas3gf python-scipy python-numpy
sudo pip install . &> install_logs &
INSTALL_PID=$!
export SPARK_HOME=./spark-1.4.1-bin-hadoop2.4/
export SPARK_CONF_DIR=./sparklingpandas/test/resources/conf
wait $WGET_PID || echo "wget finished fast"
tar -xf spark-1.4.1-bin-hadoop2.4.tgz
wait $ASSEMBLY_PID || echo "assembly finished"
nosetests --logging-level=ERROR --detailed-errors --verbosity=2 --with-coverage --cover-html-dir=./htmlcov --cover-package=sparklingpandas
pep8 --ignore=E402 sparklingpandas/
pylint -E sparklingpandas --extension-pkg-whitelist=numpy --disable=no-member
export LOCATION=`pip show sparklingpandas|grep Location| cut -d ' ' -f 2`
wait $INSTALL_PID || echo "install finished early"
tail -n 10 install_logs
echo "exit(0)" | $LOCATION/sparklingpandas/sparklingpandashell
