#!/usr/bin/env bash
if [ -z "$SPARK_HOME" ]; then
   echo "$(tput setaf 1)Error: SPARK_HOME is not set, can not run the sparkling panda shell.$(tput sgr0)"
   exit -1
fi
if [ ! -e "sparkle_dist.zip" ]; then
    zip -r sparkle_dist.zip ./sparklingpandas
fi
set -x
SPARK_EXECUTOR_MEMORY=${SPARK_EXECUTOR_MEMORY-"2000m"}
SPARK_JAVA_OPTS=${SPARK_JAVA_OPTS-"-Dspark.executor.memory=$SPARK_EXECUTOR_MEMORY -cp $CLASSPATH"}
PIP_LOCATION=`pip show sparklingpandas|grep Location| cut -d ' ' -f 2`
# If we have the shell relative to us use it, otherwise use the pip determined one
if [ -e "./sparklingpandas/shell/shell.py" ]; then
  export PYTHONSTARTUP="./sparklingpandas/shell/shell.py"
else
  export PYTHONSTARTUP="$PIP_LOCATION/sparklingpandas/shell/shell.py"
fi
python
